config_version : 0

name: tk_photoshop

version: 0.1.9

uuid: 0f637245-1581-4574-b312-430ce9ddc893

authors:
- kaitlyn.fox

description: >
 A Shotgun Pipeline Toolkit Engine for Photoshop

variants:
- [ Windows, python-2.6.4]

requires: []

commands:
- export PATH=$PATH:!ROOT!/ext/

help:
- [ "github", "chrome https://github.com/shotgunsoftware/tk-photoshop" ]
